services:
  app1:
    image: petstore:latest
    hostname: petstore01
    ports:
      - "5001:5000"
  app2:
    image: petstore:latest
    hostname: petstore01
    ports:
      - "5002:5000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "8080:80"
