version: '3'
services:
  app1:
    image: charanavvari/demoone:latest
    hostname: server01
    ports:
      - "5001:9090"
  app2:
    image: charanavvari/demotwo:latest
    hostname: server02
    ports:
      - "5002:9090"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "9000:80"
networks:
  default:
    driver: bridge
    
