name: myDemo workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: connect to EC2 by master branch push and run some commands
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: connect and execute a sample command in EC2 instance       
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}        
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${REMOTE_USER}@${REMOTE_HOST} 'ls ${TARGET} && uname -a'
          scp -i private_key hello.sh ${REMOTE_USER}@${REMOTE_HOST}:${TARGET}
          ssh -o StrictHostKeyChecking=no -i private_key ${REMOTE_USER}@${REMOTE_HOST} './hello.sh'
